import type { BlockManifest } from "@astrocms/contracts";

export const demoBuilderManifest = {
  schemaVersion: 1,
  tokens: {
    spacing: ["none", "xs", "sm", "md", "lg", "xl"],
    widths: ["content", "wide", "full"],
    columns: [1, 2, 3, 4],
    colors: ["primary", "secondary", "muted", "accent", "surface", "text"],
    breakpoints: ["mobile", "tablet", "desktop"],
  },
  blocks: [
    {
      type: "site/hero",
      label: "Hero",
      category: "Contenido",
      icon: "H",
      version: 1,
      fields: [
        { key: "title", type: "text", label: "Título", required: true, config: { maxLength: 120 } },
        { key: "description", type: "textarea", label: "Descripción", required: false, config: { maxLength: 260 } },
        { key: "alignment", type: "select", label: "Alineación", required: false, config: { options: ["left", "center", "right"] } },
      ],
      defaults: { title: "Bienvenido", description: "Edita este texto desde el builder.", alignment: "center" },
      constraints: { allowedParents: ["core/page", "core/section"] },
      capabilities: { acceptsChildren: true, duplicable: true, removable: true, hideable: true },
      hasPreviewComponent: false,
    },
    {
      type: "core/section",
      label: "Sección",
      category: "Layout",
      icon: "S",
      version: 1,
      fields: [
        { key: "width", type: "select", label: "Ancho", required: false, config: { options: ["content", "wide", "full"] } },
      ],
      defaults: { width: "content" },
      constraints: { allowedParents: ["core/page", "core/section"] },
      capabilities: { acceptsChildren: true, duplicable: true, removable: true, hideable: true },
      hasPreviewComponent: false,
    },
    {
      type: "core/heading",
      label: "Título",
      category: "Contenido",
      icon: "T",
      version: 1,
      fields: [
        { key: "text", type: "text", label: "Texto", required: true, config: { maxLength: 140 } },
        { key: "level", type: "number", label: "Nivel", required: false, config: { min: 1, max: 3 } },
      ],
      defaults: { text: "Nuevo título", level: 2 },
      constraints: { allowedParents: ["core/page", "core/section", "site/hero"] },
      capabilities: { acceptsChildren: false, duplicable: true, removable: true, hideable: true },
      hasPreviewComponent: false,
    },
    {
      type: "core/paragraph",
      label: "Párrafo",
      category: "Contenido",
      icon: "P",
      version: 1,
      fields: [
        { key: "text", type: "textarea", label: "Texto", required: false, config: { maxLength: 500 } },
      ],
      defaults: { text: "Nuevo párrafo." },
      constraints: { allowedParents: ["core/page", "core/section", "site/hero"] },
      capabilities: { acceptsChildren: false, duplicable: true, removable: true, hideable: true },
      hasPreviewComponent: false,
    },
    {
      type: "core/button",
      label: "Botón",
      category: "Contenido",
      icon: "B",
      version: 1,
      fields: [
        { key: "label", type: "text", label: "Etiqueta", required: true, config: { maxLength: 80 } },
        { key: "href", type: "text", label: "URL", required: false, config: { maxLength: 200 } },
      ],
      defaults: { label: "Botón", href: "#" },
      constraints: { allowedParents: ["core/page", "core/section", "site/hero"] },
      capabilities: { acceptsChildren: false, duplicable: true, removable: true, hideable: true },
      hasPreviewComponent: false,
    },
  ],
} satisfies BlockManifest;
